server.port=9091
#logging.level.org.apache.coyote.http11=debug
spring.messages.basename=messages,errors

# first login url not cookie
server.servlet.session.tracking-modes=cookie
# session time(minute)
server.servlet.session.timeout=1800