server:
  port: 9090
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/redis-study
    username: root
    password: chanhan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.cache: trace # cache hit ??, miss ?? ?? ??